title: My Own Reference
author: Nikolas Joyce
email: nikolasjoyce@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  All the useful commands I forget in one place. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
